apiVersion: v1
kind: PersistentVolume
metadata:
   name: auth-postgres-pv-volume
   labels:
      type: local
      app: auth-postgres
spec:
   storageClassName: manual
   capacity:
      storage: 5Gi
   accessModes:
      - ReadWriteMany
   hostPath:
      path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: auth-postgres-pv-claim
   labels:
      app: auth-postgres
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteMany
   resources:
      requests:
         storage: 5Gi
