apiVersion: apps/v1
kind: Deployment
metadata:
   name: auth-postgres-depl
spec:
   replicas: 1
   selector:
      matchLabels:
         app: auth-postgres
   template:
      metadata:
         labels:
            app: auth-postgres
      spec:
         containers:
            - name: auth-postgres
              image: postgres
              imagePullPolicy: "IfNotPresent"
              ports:
                 - containerPort: 5432
              env:
                 - name: POSTGRES_USER
                   valueFrom:
                      configMapKeyRef:
                         name: auth-postgres-config
                         key: POSTGRES_USER
                 - name: POSTGRES_PASSWORD
                   valueFrom:
                      configMapKeyRef:
                         name: auth-postgres-config
                         key: POSTGRES_PASSWORD
                 - name: POSTGRES_HOST
                   valueFrom:
                      configMapKeyRef:
                         name: auth-postgres-config
                         key: POSTGRES_HOST
                 - name: POSTGRES_DB
                   valueFrom:
                      configMapKeyRef:
                         name: auth-postgres-config
                         key: POSTGRES_DB
              volumeMounts:
                 - mountPath: /var/lib/postgresql/data
                   name: kw_auth_db
              resources:
                 limits:
                    memory: 512Mi
                    cpu: "1"
                 requests:
                    memory: 256Mi
                    cpu: "0.2"
         volumes:
            - name: kw_auth_db
              persistentVolumeClaim:
                 claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
   name: auth-postgres-srv
   labels:
      app: auth-postgres
spec:
   type: NodePort
   ports:
      - port: 5432
   selector:
      app: auth-postgres
