apiVersion: skaffold/v2alpha3
kind: Config
deploy:
   kubectl:
      remoteManifests:
         - ./infra/k8s/*
         - ./infra/k8s-dev/*
build:
   local:
      push: false
   artifacts:
      - image: law12th/auth
        context: auth
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: "src/**/*.ts"
                dest: .
