name: tests-auth

on:
   pull_request:
      paths:
         - "apps/auth/**"

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - run: cd apps/auth && yarn install && yarn run test:ci
